### ISSUE TITLE
echo_driver.sys

### ISSUE THREAD

**Issue by zagreoui** [myzxcg/RealBlindingEDR#1]
Hello, do you have the driver file for echo_driver.sys? After I downloaded it from the download link of echo_driver.sys, it was a bin file and garbled characters. If you are willing, please send the echo_driver.sys driver file to my email: Kiouizjh@proton.me. Thank you in advance.

**Comment by myzxcg** [comment]
If you rename the downloaded bin file to echo_driver.sys, you will get echo_driver.sys.
