### ISSUE TITLE
Unload Driver Error: c0000034

### ISSUE THREAD

**Issue by atanu2679** [myzxcg/RealBlindingEDR#12]
I saw in your demo video that you pre-defined the driver path inside the
code and the type as well. So I am doing the same thing, but I am
facing an error. I don't know why, so if you can help me with this,
then it would be great for me. Here is the code and output screenshot.
I only made changes to main() Func

![code](https://github.com/user-attachments/assets/064871f8-763d-45b8-b3dc-17b75a58564d)
![output](https://github.com/user-attachments/assets/5d2ea4f2-1848-40e4-a8c2-db2b8465c586)

**Please Help**

**Comment by myzxcg** [comment]
Please try the latest executable released
