### ISSUE TITLE
 list of AV/EDR process name (non-exhaustive, probably not complete)

### ISSUE THREAD

**Issue by sec13b** [myzxcg/RealBlindingEDR#13]
i didnt see where i can see the list of AV/EDR process name (non-exhaustive, probably not complete)

//Specify the location of the driver
CHAR* DrivePath = NULL;

//Set the driver name to be cleared
CONST CHAR* AVDriver[] = {

I see : Supports blinding/permanent shutdown: 
360 Security Guard, 
360 Enterprise Edition, 
Tianqing V10, 
Tencent Computer Manager, 
Tinder/Tinder Enterprise Edition, 
Kaspersky Endpoint Security, 
AsiaInfo EDR, 
Windows Defender, 
AnTian Zhijia

can you help , how i can find the sys file of sentionelone example to can "Bring Your Own Vulnerable Driver".

thank you

**Comment by myzxcg** [comment]
If you want to use other vulnerable drivers, you need to understand the code and modify the corresponding driver loading, kernel memory reading and writing functions. After the modification, the application will output the driver name that has currently registered the callback, and add the edr driver name to the CONST CHAR* AVDriver[] list.

**Comment by sec13b** [comment]
OK I will .

On my private "killer" i use only  const wchar_t* process Names for pids:

 ERAAgent.exe ekrn.exe eguiProxy.exe efwd.exeavpui.exeavpsus.exe MsMpEng.exe agentsvc.exe mfemms.exe SophosSafestore64.exe alsvc.exe msmpeng.exe sophosui.exe bccavsvc.exe psuamain.exe swi_service.exe avpsus.exe pccntmon.exe swc_service.exe


thank you.
