### ISSUE TITLE
 哥哥 ，为什么我下载了你的sys驱动 但是始终就是驱动加载不上

### ISSUE THREAD

**Issue by ljqalex** [myzxcg/RealBlindingEDR#14]
![微信图片_20241017100406](https://github.com/user-attachments/assets/afe250a6-cd07-4f1f-b63d-5d84ee1e61ce)

**Comment by myzxcg** [comment]
驱动必须要使用绝对路径，可以看看 readme

**Comment by ljqalex** [comment]
谢谢哥哥，我还以为同级目录下不加呐 真的很感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月17日(星期四) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [myzxcg/RealBlindingEDR]  哥哥 ，为什么我下载了你的sys驱动 但是始终就是驱动加载不上 (Issue #14)














 
驱动必须要使用绝对路径，可以看看 readme

**Comment by myzxcg** [comment]
不客气

**Comment by ljqalex** [comment]
哥哥，请问下，有致盲卡巴或者defender的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月17日(星期四) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [myzxcg/RealBlindingEDR]  哥哥 ，为什么我下载了你的sys驱动 但是始终就是驱动加载不上 (Issue #14)














 
不客气

**Comment by ljqalex** [comment]
哥哥 是不是在你的头文件上加上卡巴的进程名或者defender的进程名就能行了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myzxcg/RealBlindingEDR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月17日(星期四) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [myzxcg/RealBlindingEDR]  哥哥 ，为什么我下载了你的sys驱动 但是始终就是驱动加载不上 (Issue #14)





 
不客气
