### ISSUE TITLE
驱动加载行为被360拦截

### ISSUE THREAD

**Issue by furuanruan** [myzxcg/RealBlindingEDR#5]
360核晶下，原版echo_driver.sys被检测hash，微调修改hash绕过检测，但是驱动加载行为被检测，行为被拦截。

![Dingtalk_20240108145809](https://github.com/myzxcg/RealBlindingEDR/assets/90414824/4845cbf7-2563-4bbc-b221-ea50ee9cf63c)

![Dingtalk_20240108145847](https://github.com/myzxcg/RealBlindingEDR/assets/90414824/fce615cb-6d80-4967-90e6-da5afc3d7327)

**Comment by myzxcg** [comment]
既然知道被拦截的位置，你应该尝试修改一下代码进行绕过。
非常简单：替换"RealBlindingEDR"字符串为其他任意字符串即可绕过（注意有多处），下版本会改成随机字符串
<img width="1014" alt="1" src="https://github.com/myzxcg/RealBlindingEDR/assets/24795666/e2fe4e9a-36dc-46e6-89aa-d0dee354d172">

**Comment by myzxcg** [comment]
补充：可以修改成任意字符串，但这几处字符串都必须相同。

**Comment by furuanruan** [comment]
感谢师傅指点！尝试一下再来反馈

**Comment by furuanruan** [comment]
![微信截图_20240108193235](https://github.com/myzxcg/RealBlindingEDR/assets/90414824/2ed756b6-adda-438b-bedd-26a8bfb69823)
v1.2.1的试了一下，会不会还是检测echo_driver.sys驱动的特征

**Comment by myzxcg** [comment]
再改一下驱动 hash 然后用 1.2.1 试一下呢

**Comment by furuanruan** [comment]
![微信截图_20240108200933](https://github.com/myzxcg/RealBlindingEDR/assets/90414824/987cb9d4-4cd9-44d3-9b92-6d640b7924bd)
![微信截图_20240108201017](https://github.com/myzxcg/RealBlindingEDR/assets/90414824/495e10a8-1011-4a93-be5b-362a61d3186c)
我是用的v1.2.1源码本地编译的

**Comment by furuanruan** [comment]
![微信截图_20240108201539](https://github.com/myzxcg/RealBlindingEDR/assets/90414824/b276b230-1711-406c-ad07-8ec346d87e38)
对了，附上原版echo_driver.sys加载时被拦截的提示，直接当作木马了

**Comment by myzxcg** [comment]
原版驱动是肯定不行的，用的人太多了。 push 之前我测试是没有问题的。你可以尝试增大驱动的体积且修改hash。如果还不行的话，等我明天测一下再给你反馈吧

**Comment by furuanruan** [comment]
在末尾加0，增大到40k还是一样的。。。

**Comment by myzxcg** [comment]
用的v1.2.1，可正常加载执行
<img width="1619" alt="image" src="https://github.com/myzxcg/RealBlindingEDR/assets/24795666/047973db-dbdc-4828-b907-63dc86f723e1">

建议你按照我之前说的方法再测测

**Comment by furuanruan** [comment]
试了一下 开着核晶不行 关了可以

**Comment by myzxcg** [comment]
自然是开着核晶测的
