### ISSUE TITLE
驱动hash修改了，但是加载驱动被拦截如何解决，大佬求教

### ISSUE THREAD

**Issue by INotGreen** [myzxcg/RealBlindingEDR#8]
![image](https://github.com/myzxcg/RealBlindingEDR/assets/89376703/f41fae0e-d3cf-4988-acf1-34ac893cfb99)

**Comment by INotGreen** [comment]
通过调试发现，在这一行被拦截

![image](https://github.com/myzxcg/RealBlindingEDR/assets/89376703/e4d707f3-48a5-44ca-8327-6c157475f9e3)

**Comment by myzxcg** [comment]
此驱动已黑，等待发布新驱动
